fixing more pagination in research notes
publiclab/plots2 pull request #10569
Opened 2021-12-14 12:39 UTC by max-keviv

As discussed in issue #10219
I move the line 132-133 after 143

2021-12-15 06:53 UTC, TildaDares requested changes

2021-12-16 04:04 UTC, max-keviv commented on app/controllers/tag_controller.rb
> +    @paginated = true
so @paginated on line 143 is right or it should also be needed to move

2021-12-16 07:02 UTC, TildaDares commented on app/controllers/tag_controller.rb
> +    @paginated = true
The only thing that needs to change is `nodes` being sorted before line 138. The rest can stay.

2021-12-22 22:39 UTC, jywarren commented on app/controllers/tag_controller.rb
> +    @pagy, nodes = pagy(nodes.order(order_by), items: 24)
So I think we need to make a new line on 137:

`nodes = nodes.order(order_by)`

Then we can change this line to:

```suggestion
    @pagy, nodes = pagy(nodes, items: 24)
```

That way the sorting still happens above, but the pagination happens below. Sound good?

2021-12-22 22:40 UTC, jywarren commented on app/controllers/tag_controller.rb
>      @qids = Node.questions.where(status: 1)
```suggestion
    nodes = nodes.order(order_by)
    @qids = Node.questions.where(status: 1)
```

2021-12-22 22:41 UTC, jywarren commented
I added two suggestions you can accept. @TildaDares feel free to merge this once those are complete!

2021-12-23 04:48 UTC, max-keviv commented on app/controllers/tag_controller.rb
>      @qids = Node.questions.where(status: 1)
@jywarren  thank you for suggestions

2021-12-23 09:41 UTC, closed without merging

2021-12-23 09:44 UTC, max-keviv commented
open pull request at #10588