update LABELS.md
publiclab/plots2 pull request #10652
Opened 2022-01-13 10:47 UTC by tejaswari7

fix [Update Labels for Issues and PRs] #10649

2022-01-13 11:10 UTC, TildaDares requested changes

2022-01-13 11:10 UTC, TildaDares commented on doc/LABELS.md
> ++At Public Lab, we use labels to categorize and keep up with issues and pull requests.
@tejaswari7 Can you remove the `+` signs in front of the new lines you added? Thanks!

2022-01-13 11:25 UTC, TildaDares approved these changes
Thanks @tejaswari7! Great job

2022-01-13 11:28 UTC, tejaswari7 commented
thank you!! @TildaDares for guiding me

2022-01-20 10:16 UTC, govindgoel approved these changes
LGTM!

2022-01-25 09:47 UTC, merged

2022-01-25 09:47 UTC, TildaDares commented
Thanks everyone!