Fixes #10677: Fixed profile picture on profile page
publiclab/plots2 pull request #10802
Opened 2022-03-20 14:48 UTC by KarishmaVanwari

Fixes #10677 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

2022-03-23 15:06 UTC, govindgoel commented
@KarishmaVanwari can you share a screenshot as well if it is working fine

2022-03-24 10:00 UTC, KarishmaVanwari commented
@govindgoel This is what I can see locally:

![image](https://user-images.githubusercontent.com/78212650/159890761-3d71eb6b-5d97-4ed6-95b4-5721aef6053f.png)

I tried to edit the profile picture, but I am unable to do so, this is what I see : 

![image](https://user-images.githubusercontent.com/78212650/159890960-9c984635-183b-4ad5-9caa-6e72e338410f.png)

As per your comment [here](https://github.com/publiclab/plots2/issues/10677#issuecomment-1026567094), does it mean that the changes will reflect only when in production (since I am unable to check it locally)? Do correct me if I'm wrong. Thanks!

2022-03-25 22:42 UTC, TildaDares commented
Hi @KarishmaVanwari, to upload a picture you would have to install `ImageMagick`. https://github.com/publiclab/plots2/blob/6be83ac1945a4e1ba5b6f8e3093d11168765f432/doc/PREREQUISITES.md#image-libraries-optional

2022-04-03 10:51 UTC, KarishmaVanwari commented
> Hi @KarishmaVanwari, to upload a picture you would have to install `ImageMagick`. https://github.com/publiclab/plots2/blob/6be83ac1945a4e1ba5b6f8e3093d11168765f432/doc/PREREQUISITES.md#image-libraries-optional

Thank you so much @TildaDares! I was successfully able to upload the image. The profile picture is visible now on the profile page, as you can see :
![image](https://user-images.githubusercontent.com/78212650/161424078-4f71e9f0-2dcb-471e-966e-d999131e4001.png)


@govindgoel @TildaDares I hope this works. Apologies for delay since I had been a little busy with my university exams. Thanks!

2022-04-04 17:41 UTC, TildaDares requested changes

2022-04-06 09:33 UTC, KarishmaVanwari commented on app/views/users/profile.html.erb
> +      <img src="<%= @profile_user.profile_image(:medium) %>" class="rounded-circle" id="profile-photo" style="width:50%;margin-bottom:20px;" />
Done! @TildaDares

2022-04-07 19:21 UTC, TildaDares approved these changes
Tested on my local env. It works!!

Thanks @KarishmaVanwari. Great work!

2022-04-11 04:17 UTC, KarishmaVanwari commented
Thank you @TildaDares!!!

2022-04-12 20:36 UTC, jywarren commented
My apologies, i tried resolving the merge conflicts and made a mistake, but I fixed it. Once these tests pass we are good to merge! Thanks!!!

2022-04-12 20:48 UTC, merged

2022-04-12 20:48 UTC, jywarren commented
OK, excellent! Thank you!!!