Update _flags.html.erb
publiclab/plots2 pull request #10966
Opened 2022-04-06 17:15 UTC by Dapper50

Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

2022-04-06 17:32 UTC, TildaDares commented
Hi @Dapper50, can you add the issue number in the description above? It should be in the format `fixes #0000`. Thanks!

2022-04-06 17:37 UTC, Dapper50 commented
@TildaDares done

2022-04-07 07:27 UTC, TildaDares commented
@Dapper50 The issue number is the number at the top of the issue you were assigned. It starts with a #

2022-04-07 07:42 UTC, Dapper50 commented
@TildaDares apologies for mix up, I have updated it.

2022-04-07 18:36 UTC, TildaDares commented
Hi @Dapper50, I can't find the issue number.

2022-04-07 18:52 UTC, TildaDares requested changes

2022-04-07 18:52 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +    select_all();
```suggestion
      select_all();
```

2022-04-07 19:00 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +   $("#batch-ban").bind('click', function (e) { //batch ban
```suggestion
  $("#batch-ban").bind('click', function (e) { //batch ban
```

2022-04-07 19:00 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +     batch_nav("batch_ban");
```suggestion
    batch_nav("batch_ban");
```

2022-04-07 19:00 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +   });
```suggestion
  });
```

2022-04-07 19:00 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +    $("#batch-unban").bind('click', function (e) { //batch ban
```suggestion
  $("#batch-unban").bind('click', function (e) { //batch ban
```

2022-04-07 19:01 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +     batch_nav("batch_unban");
```suggestion
    batch_nav("batch_unban");
```

2022-04-07 19:01 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +    });
```suggestion
  });
```

2022-04-07 19:01 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +    $("#delete-batch").bind('click', function (e) { // batch delete
```suggestion
  $("#delete-batch").bind('click', function (e) { // batch delete
```

2022-04-07 19:01 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +      batch_nav("batch_delete");
```suggestion
    batch_nav("batch_delete");
```

2022-04-07 19:02 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +   });
```suggestion
  });
```

2022-04-07 19:02 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +    $('#pageselect').change(function () {
```suggestion
  $('#pageselect').change(function () {
```

2022-04-07 19:02 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +      pagination("#pageselect", "/spam2/flags/filter/");
```suggestion
    pagination("#pageselect", "/spam2/flags/filter/");
```

2022-04-07 19:02 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +    });
```suggestion
  });
```

2022-04-07 19:03 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +   $('#spammed').on('click', function () { //spam filter
```suggestion
  $('#spammed').on('click', function () { //spam filter
```

2022-04-07 19:03 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +      search_table("spammed", "/spam2/flags/filter/");
```suggestion
    search_table("spammed", "/spam2/flags/filter/");
```

2022-04-07 19:03 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +    });
```suggestion
  });
```

2022-04-07 19:03 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +    $('#unmoderated').on('click', function () { // unmoderated filter
```suggestion
  $('#unmoderated').on('click', function () { // unmoderated filter
```

2022-04-07 19:04 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +      search_table("unmoderated", "/spam2/flags/filter/");
```suggestion
    search_table("unmoderated", "/spam2/flags/filter/");
```

2022-04-07 19:04 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +    });
```suggestion
  });
```

2022-04-07 19:04 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +    $('#page').on('click', function () { // page filter
```suggestion
  $('#page').on('click', function () { // page filter
```

2022-04-07 19:05 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +     search_table("page", "/spam2/flags/filter/");
```suggestion
    search_table("page", "/spam2/flags/filter/");
```

2022-04-07 19:05 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +   });
```suggestion
  });
```

2022-04-07 19:05 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +   $('#note').on('click', function () { // note filter
```suggestion
  $('#note').on('click', function () { // note filter
```

2022-04-07 19:05 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +      search_table("note", "/spam2/flags/filter/");
```suggestion
    search_table("note", "/spam2/flags/filter/");
```

2022-04-07 19:05 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +    });
```suggestion
  });
```

2022-04-07 19:05 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +   $('#reset').on('click', function () { // all filter
```suggestion
  $('#reset').on('click', function () { // all filter
```

2022-04-07 19:06 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +    });
```suggestion
  });
```

2022-04-07 19:06 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
> +   $('#unflag-node').tooltip({ boundary: 'window' });
```suggestion
  $('#unflag-node').tooltip({ boundary: 'window' });
```

2022-04-07 19:07 UTC, TildaDares commented on app/views/spam2/_flags.html.erb
>    });
```suggestion
});
```

2022-04-07 19:07 UTC, TildaDares commented
Feel free to commit all of those suggestions!!

2022-04-07 19:51 UTC, Dapper50 commented
Hi @TildaDares i have update the issue number with  PR #10966

2022-04-12 17:32 UTC, TildaDares commented
@Dapper50 What do you need help with?

2022-04-13 18:30 UTC, Dapper50 commented
@TildaDares the changes I made I wanted to confirm if it is correct, or if I would require to redo it

2022-04-13 18:32 UTC, TildaDares commented
@Dapper50 You don't have to redo anything. All you have to do is press those `Commit suggestion` buttons and we should be good.

2022-04-13 18:48 UTC, Dapper50 commented
@TildaDares okay i have done that

2022-04-13 18:59 UTC, TildaDares commented
@Dapper50 Can you look for that button and click it? After clicking, you should see more `Commit suggestion` to click.

<img width="898" alt="Screenshot 2022-04-13 at 19 59 02" src="https://user-images.githubusercontent.com/63427719/163251150-36c0edd2-1b30-423b-bf69-d4e3a9ee0b3b.png">

2022-04-13 19:11 UTC, Dapper50 commented
@TildaDares apologies for the mix up i just finished doing it.

2022-04-13 19:15 UTC, TildaDares approved these changes
Great job @Dapper50. Thank you!!

2022-04-14 16:49 UTC, merged

2022-04-14 16:50 UTC, TildaDares commented
Congratulations @Dapper50 🎉

2022-04-14 18:39 UTC, Dapper50 commented
@TildaDares thank you so much for your support