Fix indentation in _users.html.erb file
publiclab/plots2 pull request #11033
Opened 2022-04-11 14:25 UTC by kirteeprajapati

#11023
Completed my first timer issue

Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

2022-04-12 06:14 UTC, debck approved these changes
@kirteeprajapati Great work !

2022-04-12 06:47 UTC, TildaDares requested changes

2022-04-12 21:47 UTC, kirteeprajapati commented on app/views/spam2/_users.html.erb
> ++    select_all();
Yes i did it is it fine now @TildaDares Kindly review

2022-04-13 06:41 UTC, TildaDares requested changes

2022-04-13 06:41 UTC, TildaDares commented on app/views/spam2/_users.html.erb
> +   var table = table_main("#flag_table");
```suggestion
  var table = table_main("#flag_table");
```

2022-04-13 06:41 UTC, TildaDares commented on app/views/spam2/_users.html.erb
> +   $("#all").click(function () { //select all button
```suggestion
  $("#all").click(function () { //select all button
```

2022-04-13 06:41 UTC, TildaDares commented on app/views/spam2/_users.html.erb
> +     select_all();
```suggestion
    select_all();
```

2022-04-13 17:28 UTC, TildaDares approved these changes
Great work @kirteeprajapati. Thank you!!

2022-04-13 17:29 UTC, merged

2022-04-13 17:29 UTC, TildaDares commented
Congratulations @kirteeprajapati 🎉

2022-04-14 09:21 UTC, kirteeprajapati commented
> Congratulations @kirteeprajapati 🎉

Thank you so much @TildaDares ✨😊