fixed typos and indentation in _spam.html.erb
publiclab/plots2 pull request #11043
Opened 2022-04-12 10:29 UTC by imranburki

Fixes #10984 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

2022-04-12 16:36 UTC, TildaDares requested changes

2022-04-12 16:38 UTC, TildaDares requested changes

2022-04-12 16:38 UTC, TildaDares commented on app/views/spam2/_spam.html.erb
> +          <a class="nav-link btn btn-light border disabled text-dark d-inline-flex border-curve" id="batch-spam" ><i class=" pt-1 pr-2 fa fa-ban text-danger" data-toggle="tooltip" data-placement="top
```suggestion
          <a class="nav-link btn btn-light border disabled text-dark d-inline-flex border-curve" id="batch-spam" ><i class=" pt-1 pr-2 fa fa-ban text-danger" data-toggle="tooltip" data-placement="top" title="Mark selected items as spam and ban users"></i>Spam</a>
```

2022-04-12 16:49 UTC, TildaDares requested changes

2022-04-12 16:49 UTC, TildaDares commented on app/views/spam2/_spam.html.erb
> +    </div>
```suggestion
```

2022-04-13 06:28 UTC, TildaDares requested changes

2022-04-13 06:28 UTC, TildaDares commented on app/views/spam2/_spam.html.erb
> +
```suggestion
```

2022-04-13 06:47 UTC, TildaDares commented
@imranburki I think this is the only thing left to do.

> Also, can you remove `package.json` and `yarn.lock` from this PR? Thanks!

2022-04-13 07:10 UTC, imranburki commented
@TildaDares I deleted/removed yarn.lock and package.json . It show conflict error. please help me what should i do?

2022-04-13 07:44 UTC, TildaDares commented
@imranburki You're not supposed to delete the files. All you have to do is copy the contents of `yarn.lock` and `package.json` from this repo and paste into your local files. After that, do a push.

2022-04-13 17:26 UTC, TildaDares commented
@imranburki I tried removing `yarn.lock` from my end but it didn't work. What you have to do is copy the contents of `yarn.lock` from https://github.com/publiclab/plots2/edit/main/yarn.lock and paste it into your local version of `yarn.lock`. After that do a push.

2022-04-13 19:01 UTC, TildaDares commented
@imranburki Is it possible to close this PR and start afresh?

2022-04-13 19:10 UTC, imranburki commented
@TildaDares yes, please

2022-04-13 19:22 UTC, closed without merging

2022-04-13 19:23 UTC, imranburki commented
closed pull request