hide wiki edit button if user is not logged in , file _like.html.erb , Issue #11354
publiclab/plots2 pull request #11368
Opened 2022-08-27 20:57 UTC by nickmendezFlatiron

Made changes specified in [Issue #11354](https://github.com/publiclab/plots2/issues/11354).
Removed the mentioned lines of code in _like.html.erb file and added the new lines of code.
Fixes #11354  

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [✔️ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ✔️] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [✔️ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ✔️] screenshots/GIFs are attached 📎 in case of UI updation
* [ ✔️] ask `@publiclab/reviewers` for help, in a comment below

2022-08-28 00:51 UTC, nickmendezFlatiron commented
@publiclab/reviewers 
I made the changes mentioned but there is a tests/system-tests error. 

`=================[Screenshot]: tmp/screenshots/failures_test_edit_wiki.png
ERROR PostTest#test_edit_wiki (199.06s)
Minitest::UnexpectedError:         Capybara::ElementNotFound: Unable to find css "a.btn-circle:first-of-type .fa-pencil"
            test/system/post_test.rb:96:in block in <class:PostTest>'`

This error is referring to the test/system/post_test.rb file , the "edit wiki" test.

2022-08-28 21:26 UTC, TildaDares requested changes
Feel free to just click the `Commit Suggestion` button. Thank you!

2022-08-28 21:26 UTC, TildaDares commented on app/views/like/_like.html.erb
> +          <i class="ff fa fa-lock"></i>
This should fix the failing test @nickmendezFlatiron. Sorry for the inconvenience!
```suggestion
          <i class="ff fa fa-pencil"></i>
```

2022-08-29 16:40 UTC, TildaDares approved these changes
Amazing work @nickmendezFlatiron. Thank you!!

2022-08-29 16:41 UTC, TildaDares commented
@jywarren Most of the tests are failing with this error
```
{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```

2022-08-30 17:35 UTC, merged

2022-08-30 17:35 UTC, TildaDares commented
Congratulations on merging your PR @nickmendezFlatiron 🎉

2022-09-01 03:47 UTC, nickmendezFlatiron commented
@TildaDares thank you for you help!