Resolving First timers issue template grammatical mistakes
publiclab/plots2 pull request #11410
Opened 2022-09-12 18:36 UTC by ojninja16

Fixes #11395  

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

2022-09-13 14:17 UTC, ojninja16 commented
@TildaDares Please review....

2022-09-14 06:04 UTC, TildaDares requested changes
Hi @ojninja16, feel free to just click the `Commit suggestion` button. Thanks!

2022-09-14 06:04 UTC, TildaDares commented on .github/first-timers-issue-template.md
> +If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from underre
```suggestion
If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from underrepresented groups in free and open-source software!
```

2022-09-14 06:04 UTC, TildaDares commented on .github/ISSUE_TEMPLATE/--first-timers-only.md
> +If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from underre
```suggestion
If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from underrepresented groups in free and open-source software!
```

2022-09-15 17:10 UTC, TildaDares approved these changes
Amazing work @ojninja16. Thank you!!

2022-09-15 17:10 UTC, merged

2022-09-15 17:51 UTC, ojninja16 commented
Glad, I could help.....thanks for the opportunity @TildaDares