Update 404.html
publiclab/plots2 pull request #11495
Opened 2022-10-17 00:17 UTC by liliyao2022

Replaced the nav tag with the header tag.

Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

2022-10-17 00:17 UTC, liliyao2022 commented
replaced the nav tag with the header tag.

2022-10-21 11:54 UTC, TildaDares requested changes

2022-10-21 11:54 UTC, TildaDares commented
Hi @liliyao2022, can you add a link to the issue? 

> One thing that can help to get started is to make sure you've included a link back to the original issue you're solving, in the
> format fixes #0000 (for example)

2022-11-10 21:53 UTC, TildaDares commented
Thank you for taking the time to work on this PR but the issue has been resolved in #11539.

2022-11-10 21:53 UTC, closed without merging