Update spam2_controller.rb
publiclab/plots2 pull request #11515
Opened 2022-10-19 11:46 UTC by JeffyDave

My FTO issue for Public Lab

I made changes to the issue to serve as my FTO
![Screen Shot 2022-10-19 at 12 45 16 PM](https://user-images.githubusercontent.com/106249556/196681924-368f76dd-45e7-4117-ac6c-3e930b0df596.png)

Fixes ##11498
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

2022-10-19 11:49 UTC, JeffyDave commented
@TildaDares Please can you review this?

2022-10-19 12:11 UTC, JeffyDave commented
@TildaDares I have made the changes but it's still showing that I haven't, is there any way you could help me?
![Uploading Screen Shot 2022-10-19 at 1.06.18 PM.png…]()

2022-10-19 12:26 UTC, JeffyDave commented
@TildaDares I have made the changes, I don't know why a test failed, This is a screenshot of the error
![Screen Shot 2022-10-19 at 1 06 18 PM](https://user-images.githubusercontent.com/106249556/196690353-8d045334-d1fe-415e-8bd7-4514719b4f7b.png)

2022-10-19 16:25 UTC, TildaDares requested changes
Hi @JeffyDave, removing the extra plus sign should fix the error. Thank you!

2022-10-19 19:58 UTC, JeffyDave commented on app/controllers/spam2_controller.rb
> ++                  @nodes.where(status: 1).order('changed DESC')
Thank you very much.

2022-10-19 20:06 UTC, JeffyDave commented on app/controllers/spam2_controller.rb
> +                  @nodes.where(status: 1).order('changed DESC')
I have made the necessary change.

2022-10-20 07:32 UTC, TildaDares approved these changes
Amazing work @JeffyDave. Thank you!!

2022-10-20 07:34 UTC, merged

2022-10-20 07:35 UTC, TildaDares commented
Congratulations on merging your PR @JeffyDave 🎉🎉

2022-10-20 07:39 UTC, 7malikk commented
Congratulations @JeffyDave 🍾🎊🎉