Changes .length & .count to .size
publiclab/plots2 pull request #8402
Opened 2020-09-16 15:59 UTC by Hassanelashram

I changed all the instances as asked.
At first I misunderstood and created a branch locally where I edited all the .count and .length in ruby files in the whole codebase.
so if that is something that needs to be done at some point let me know and I could make a PR with the changes as well.

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

2020-09-17 13:50 UTC, avats-dev commented
@Hassanelashram thanks for working on this. Could you mention the concerned issue in your PR, as it will help others review. Thanks :+1:

2020-09-17 17:19 UTC, Hassanelashram commented
> @Hassanelashram thanks for working on this. Could you mention the concerned issue in your PR, as it will help others review. Thanks 👍

Hey, yes sorry, it's my first time contributing in an open source: https://github.com/publiclab/plots2/pull/8402#issuecomment-694248678

2020-09-17 17:41 UTC, avats-dev commented
> > @Hassanelashram thanks for working on this. Could you mention the concerned issue in your PR, as it will help others review. Thanks +1
> 
> Hey, yes sorry, it's my first time contributing in an open source: [#8402 (comment)](https://github.com/publiclab/plots2/pull/8402#issuecomment-694248678)

Hey @Hassanelashram , thanks for your contribution and welcome to publiclab community. We want to help first timers contribute. You can always ping back if you're stuck or need any help.

#8402 is this PR, not the issue you're resolving. See this:
> It's very important to link your PR to the issue that it intends to resolve, as this can:
> 
>     * help others check if PR is any good for what it is intended.
> 
>     * automatically close that issue when the PR is merged.
> 
>     * help in better workflow of the codebase.
> 
> 
> To link your PR to the issue, edit your comment (the first one, i.e. one with which you have opened this PR) and you'll see something like "**Fixes #0000 (<=== Add issue number here)**". This is even the first line of your comment. You have to replace **0000** here with the issue number concerned with your PR, and leave everything else as it is. **Don't remove the # as it is crucial and creates the link in between.**
> 
> If you're still unsure and having problems, watch this as an example.
> ![Peek 2020-08-22 23-58](https://user-images.githubusercontent.com/35889327/90963241-ce624300-e4d3-11ea-80f3-bc8b29f0cdae.gif)

2020-09-17 19:45 UTC, cesswairimu requested changes
Sorry forgot to indicate the appropriate places that the replacement will work.

2020-09-17 19:45 UTC, cesswairimu commented on app/models/tag.rb
> +    start.to_date.step(fin.to_date, 7).size
hello, seems a couple of things won't work here. Lets leave this as `.count`  `.size` will return nil here

2020-09-17 19:45 UTC, cesswairimu commented on app/models/tag.rb
> +    week = start.to_date.step(fin.to_date, 7).size
lets also leave `.count` the same here

2020-09-17 19:45 UTC, cesswairimu commented on app/models/tag.rb
> +                 .collect(&:nid) # take top 5
Not sure if you updated this by mistake. Lets please leave it as is

2020-09-17 19:45 UTC, cesswairimu commented on app/models/tag.rb
> +        .size(:all)
lets also leave this as `.count`... `.size(:all)` is not a valid rails method

2020-09-17 19:45 UTC, cesswairimu commented on app/models/tag.rb
> +        .size(:all)
lets also leave this as .count... .size(:all) is not a valid rails method

2020-09-17 19:45 UTC, cesswairimu commented on app/models/tag.rb
> +        ).size(:all)
lets also leave this as .count... .size(:all) is not a valid rails method

2020-09-17 19:45 UTC, cesswairimu commented on app/models/tag.rb
> +      ).size(:all)
lets also leave this as .count... .size(:all) is not a valid rails method

2020-09-17 19:45 UTC, cesswairimu commented on app/models/tag.rb
> +    self.size = NodeTag.where(tid: tid).size
lets leave the check for status here

` self.count = NodeTag.joins(:node).where(tid: tid).where('node.status = 1').size`

2020-09-18 07:28 UTC, Hassanelashram commented
@cesswairimu Thank you so much! I fixed them now, regarding the checks, it seems like rubocop is failing for a missing space ?

2020-09-18 18:47 UTC, cesswairimu commented
Thanks. Not sure why travis is still failing, I will pull this and check locally if there are other replacements that are not working. 
As for rubocop yes it recommends we have space before and after `{` and `}`

2020-09-19 08:52 UTC, Hassanelashram commented
> Thanks. Not sure why travis is still failing, I will pull this and check locally if there are other replacements that are not working.
> As for rubocop yes it recommends we have space before and after `{` and `}`

Cool thanks, 
and for the spaces I am confused as I see that line 380 already has the spaces @cesswairimu

2020-09-20 08:36 UTC, cesswairimu commented on app/models/tag.rb
> +      nids = nids.group_by{ |v| v }.map{ |k, v| [k, v.size] }
No worries @Hassanelashram , what I meant is this should be like 
`nids = nids.group_by { |v| v }.map { |k, v| [k, v.size] }`

2020-09-28 11:35 UTC, cesswairimu commented
Hi @Hassanelashram, we encourage contributors to take one first-timer-only issue( These are issues with that label) and leave the others for new contributors coming in. Since this PR we merger one, closing this to give another new contributor a chance to work on it. You can look for issues with the label 'help-wanted' .Thanks

2020-09-28 11:35 UTC, closed without merging