Replaced .count with .size in Line 49
publiclab/plots2 pull request #8491
Opened 2020-10-08 17:37 UTC by Annysah

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

2020-10-08 21:06 UTC, cesswairimu requested changes
Great job here :100:  almost there

2020-10-08 21:06 UTC, cesswairimu commented on app/views/search/all_content.html.erb
> +m <div class="col-md-2">
Seems like you added this `m` by mistake. Kindly edit the file and remove the `m` at the beginning of the file and commit.
you can find it here https://github.com/Annysah/plots2/blob/patch-6/app/views/search/all_content.html.erb.

2020-10-09 18:02 UTC, RuthNjeri commented
Good job @Annysah, I'm just curious if changing .count to .size also applied to the queries too? Since multiple models use .count.. @cesswairimu can confirm this?

2020-10-09 18:09 UTC, RuthNjeri commented
Also, there are some files that have been left out in the view like
[Form Partial] (https://github.com/publiclab/plots2/blob/main/app/views/locations/_form.html.erb#L48)
[Card Partial] (https://github.com/publiclab/plots2/blob/main/app/views/notes/_card.html.erb#L28) and line 29

and some more.. 

If you use Visual Studio Code as an editor, you can search the word `count` and you'll see all the files that reference it, that's what I have done @Annysah, if you are not using Visual Studio Code, I think you can just do a global search within those files, or use the global search of your editor.

<img width="486" alt="Screenshot 2020-10-09 at 21 08 21" src="https://user-images.githubusercontent.com/7622875/95617116-91e2aa80-0a73-11eb-9d37-efa2f66644d7.png">

2020-10-09 18:25 UTC, cesswairimu commented
Yeah it applies to some of them, we have other issues opened for some of these files. sometimes `.size` does  not  replace `.count`  seamlessly  e.g on this line https://github.com/publiclab/plots2/blob/main/app/models/node.rb#L197 using `.size` returns nil  but .count returns 0. That's why replacing a couple of files per issue is crucial so that we don't break existing functionality.  Thanks

2020-10-09 18:33 UTC, RuthNjeri commented
It's clear now, thanks @cesswairimu

2020-10-10 09:18 UTC, Annysah commented
Hello @cesswairimu thanks for the review, I have removed the m which was mistakenly added.
Can I get a review?

2020-10-10 09:22 UTC, Annysah commented
Thanks @RuthNjeri

2020-10-11 09:21 UTC, Tlazypanda approved these changes
@Annysah Looking good :tada: Thanks for working on this!!

2020-10-11 09:32 UTC, Annysah commented
Thank you! @Tlazypanda

2020-10-12 13:15 UTC, cesswairimu approved these changes
Awesome all good now :tada:

2020-10-12 13:18 UTC, cesswairimu commented
Thanks @Annysah for working on this :rocket:  would you like to close the other pull requests since we updated all files here? 
 Thanks @Tlazypanda and @RuthNjeri  for the reviews :tada:

2020-10-12 13:19 UTC, merged

2020-10-12 18:12 UTC, Annysah commented
Oh my!!! I'm so excited that my PR was merged!!!