Change t to translation in dashboard/_comment_moderate
publiclab/plots2 pull request #8509
Opened 2020-10-09 16:37 UTC by ana-vela

Fixes #[6598 ](https://github.com/publiclab/plots2/issues/6598)

Changed the function named t(....) to be named as translation(...) on lines 4, 5, 6, and 8.

* [ ✅] PR is descriptively titled 📑 and links the original issue above 🔗
* [✅ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [✅ ] code is in uniquely-named feature branch and has no merge conflicts 📁

2020-10-09 17:01 UTC, jywarren requested changes
Hi, this looks great! Can you share a screenshot of the changes so we can just be sure it worked? You can do this by opening GitPod and it will boot up your changes!

2020-10-09 17:55 UTC, ana-vela commented
Sure! When I connect with Gitpod, this is what I see. Is there something else I need to do? Or is a different screenshot needed? Thanks for your time! 

<img width="1430" alt="public-lab-6598" src="https://user-images.githubusercontent.com/20852847/95615786-07278e80-0a26-11eb-8625-87c33a9d7ed8.png">

2020-10-09 19:29 UTC, jywarren commented
Those definitely show that the site is running, which is great!

Well if you are able to create an account and post a comment on the site that's running in Gitpod, and then, perhaps, log in with `admin`/`password` to see what the comment looks like on the dashboard, we can see it in situ! But if you run into any trouble with that, I'm happy to give it a go as well. Thanks so much!

2020-10-10 05:04 UTC, ana-vela commented
I was able to create a user account to test this change. I could add comments to an existing blog post. Then I logged in as admin and was given the option to the approve the comments. Once these buttons were clicked, the comments were added and no errors appeared. 

<img width="1051" alt="public-lab-approve-comment" src="https://user-images.githubusercontent.com/20852847/95646122-8a76cd80-0a82-11eb-86b3-7c21902af81f.png">

<img width="981" alt="public-lab-comments-approved" src="https://user-images.githubusercontent.com/20852847/95646237-9b740e80-0a83-11eb-9c3d-803607d97fe9.png">


Is the function different for comments to questions? I wanted to add a comment to a question I added, but when I clicked the link to access that question, I saw this error:

<img width="1346" alt="public-lab-error" src="https://user-images.githubusercontent.com/20852847/95646168-f0fbeb80-0a82-11eb-819c-b129b5df9ccc.png">

2020-10-11 23:23 UTC, jywarren commented
Hi, I think it should be the same but I believe this template is used only on the dashboard, when view it comments there! Can you try viewing your comment in that page and then your changes should appear!

Thank you, much appreciated!! You're doing super well here!

2020-10-12 15:26 UTC, ana-vela commented
I still got an error when I logged out and tried to see the question. I wonder if this is related to being in the dev environment. I believe the initial issue is resolved. Let me know if there is anything else needed. Thank you!

2020-10-16 15:13 UTC, jywarren commented
Oh, i'm so sorry, yes, this is something we're trying to resolve in https://github.com/publiclab/plots2/pull/8499 because GitPod has trouble with those pages for some reason. I can download and run this in a couple days and will merge it then - thank you so much!

2020-10-18 17:44 UTC, ana-vela commented
Thank you!

2020-10-21 00:31 UTC, jywarren commented
This is all good! Thank you so much!!

2020-10-21 00:31 UTC, merged

2020-10-21 00:31 UTC, jywarren commented
Great work!!!

2020-10-26 13:41 UTC, ana-vela commented
Thank you, @jywarren! I saw that a comment was successfully posted two days ago on the stable dev site. (I tried to add a comment on that site a few days ago, but it is pending approval.) 

<img width="1330" alt="Screen Shot 2020-10-26 at 7 38 11 AM" src="https://user-images.githubusercontent.com/20852847/97179549-8e7f3c80-175e-11eb-92b3-50424f1df278.png">