Fixes part of #5352: Blog redesign next steps
publiclab/plots2 pull request #8608
Opened 2020-10-18 13:26 UTC by Cadreia

Fixes #5352 (<=== Add issue number here)
![blog-plots2](https://user-images.githubusercontent.com/40563356/96368737-836c5100-114d-11eb-9b5d-4650c8b260ed.png)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

2020-10-18 13:34 UTC, Cadreia commented
@publiclab/reviewers, please can you review this pull request?

2020-10-30 18:37 UTC, Cadreia commented
@cesswairimu can you please review this pr?

2020-11-05 22:44 UTC, jywarren commented
Hiiii @Cadreia --- i'm so sorry we missed this! This looks really great. I'm reviewing it -- will go through more carefully tomorrow!

2020-11-05 23:00 UTC, jywarren commented
I just resolved the conflicts to get this merge-able. Then i'll try it out!

2020-11-10 17:48 UTC, jywarren requested changes
Just making some smaller tweaks, and replacing the Categories with an admin-modifiable Feature code snippet! This looks great, though!!!!

2020-11-10 17:48 UTC, jywarren commented on app/controllers/tag_controller.rb
> +    @alltags = Tag.first(6)
This looks really great - i'm just going to make a small suggested change here so we can set the featured topics manually. Thanks, @Cadreia !!!!

```suggestion
```

2020-11-10 17:48 UTC, jywarren commented on app/views/comments/_form.html.erb
> +                <% if is_new_contributor %>
I think maybe this section was an unintended change?

2020-11-10 17:48 UTC, jywarren commented on app/views/tag/blog2.html.erb
> +            <a href="/research">RESEARCH</a>
```suggestion
            <a href="/tags">TOPICS</a>
```

2020-11-10 17:48 UTC, jywarren commented on app/views/tag/blog2.html.erb
> +               <div id="categories-content">
I'll make a direct edit to this section...

2020-11-10 17:51 UTC, jywarren approved these changes

2020-11-10 17:51 UTC, jywarren commented on app/views/comments/_form.html.erb
> +                <% if is_new_contributor %>
I removed it!

2020-11-10 19:00 UTC, jywarren commented
OK! I think we are good here for a first round! Thank you so much, @Cadreia for this big contribution, it's great! Let's merge and we can refine more in follow-up!

2020-11-10 19:00 UTC, merged

2020-11-17 17:00 UTC, jywarren commented
Just confirming that images do exist on this, it's just that stable.publiclab.org doesn't have all the latest image assets as it's a test server!