[Outreachy]Typeahead Search
publiclab/plots2 pull request #9066
Opened 2021-01-22 20:11 UTC by RuthNjeri

Fixes #8838

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

<img width="374" alt="Screenshot 2021-01-22 at 23 00 55" src="https://user-images.githubusercontent.com/7622875/105540287-0847a780-5d07-11eb-9e16-0d035acc3b2c.png">

2021-01-26 21:38 UTC, jywarren commented
Ooooohhhhhh!!!!!! Ok, reviewing this now!

2021-01-26 21:39 UTC, jywarren approved these changes
This looks great. Unfortunately https://stable.publiclab.org is offline right now but this might bear some performance testing with a full database. That said, if it's all the same code as at https://publiclab.org/tags, then we should be OK!!!

2021-01-26 21:41 UTC, jywarren commented on app/views/dashboard_v2/_sidebar.html.erb
> +        <%# Search topics %>
```suggestion
```

2021-01-26 21:42 UTC, jywarren requested changes

2021-01-26 21:42 UTC, jywarren commented on app/views/dashboard_v2/_sidebar.html.erb
> +        <br/><br/>
```suggestion
        <h3>Search topics</h3>
```

What if we did this, and also converted other instances of `<%# ... %>` into regular HTML comments like `<!-- ... -->`? I think that could be nice to leave the rest of the page just normal HTML and not insert Ruby just to make a comment. Not a big deal, but stylistically nice!

2021-01-26 21:44 UTC, jywarren commented
These changes were so small i just added a commit. Then we can merge!

2021-01-26 22:33 UTC, merged

2021-01-27 13:47 UTC, RuthNjeri commented
Thanks @jywarren! Using  the HTML style for comments does make sense...I'll do that in the future.