-> Update README.md
publiclab/plots2 pull request #9246
Opened 2021-03-02 10:30 UTC by fannyibz

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

2021-03-02 11:22 UTC, fannyibz commented
Hi, 
I did my first pull request. I don't understand why "tests / unit-tests (pull_request) Failing after 1m — unit-tests" is failing.
Could you help me please?
Thanks a lot

2021-03-02 12:08 UTC, cesswairimu commented
Hey @fannyibz , we have one test fails sometimes on this...I will close this and reopen to if it passes...In the meantime, kindly add the issue link to the issue this pull request fixes on your pull request on this line "Fixes issue_link" this will help other contributors while reviewing your changes. It also helps in automatically closing the issue when the pull request is merged. Thanks

2021-03-02 12:25 UTC, cesswairimu requested changes
Everything else looks good and we should be good to merge after the updates...Thanks for working on this

2021-03-02 12:25 UTC, cesswairimu commented on README.md
> ++[![first-timers-only-friendly](https://img.shields.io/badge/first--timers--only-friendly-blue.svg?style=flat-square)](https://code.publiclab.org#r=all)
@fannyibz kindly remove the `+`  at the beginning of the lines you changes...on the issue description the `+` represented the lines that were to be added  and the lines starting with `-` were to be remove...sorry for the confusion.

2021-03-02 12:25 UTC, cesswairimu commented on README.md
> ++* Tagging and [topically-based groups and content organization](https://publiclab.org/tags)
remove the `+` here

2021-03-02 12:25 UTC, cesswairimu commented on README.md
> ++* A privacy-sensitive, Leaflet-based [location tagging system](https://github.com/publiclab/leaflet-blurred-location/) and [community map](https://publiclab.org/people)
remove the `+` here too

2021-03-03 09:30 UTC, cesswairimu approved these changes
Great :tada: thanks for working on this

2021-03-03 09:31 UTC, merged